---
id: linode
label: Linode
version: "0.2"

url_referral: https://www.linode.com/?r=a278f28e12e5e4e08adc41d8491a1988363e80d6
url_apikey: https://manager.linode.com/profile/api
url_provider: https://www.linode.com

credentials:
    - label: Linode API key
      id: apiKey
      private: true

sizes:
    - label: Linode 1024 (8 Cores - 1024 MB - 24GB - 2TB)
      id: 1
    - label: Linode 2048 (8 Cores - 2048 MB - 48GB - 4TB)
      id: 3
    - label: Linode 4096 (8 Cores - 4096 MB - 96GB - 8TB)
      id: 5
    - label: Linode 8192 (8 Cores - 8192 MB - 192GB - 16TB)
      id: 6
    - label: Linode 16384 (8 Cores - 16384 MB - 384GB - 20TB)
      id: 7
    - label: Linode 24576 (8 Cores - 24576 MB - 576GB - 20TB)
      id: 8
    - label: Linode 32768 (8 Cores - 32768 MB - 768GB - 20TB)
      id: 9
    - label: Linode 40960 (8 Cores - 40960 MB - 960GB - 20TB)
      id: 10

locations:
    - label: "Dallas, TX, USA"
      id: 2
    - label: "Fremont, CA, USA"
      id: 3
    - label: "Atlanta, GA, USA"
      id: 4
    - label: "Newark, NJ, USA"
      id: 6
    - label: "London, England, UK"
      id: 7
    - label: "Tokyo, Japan, JP"
      id: 8

defaults:
    image:
        id: 124
        name: Ubuntu 14.04.1 64bit LTS
    location:
        id: 2
        name: "Dallas, TX, USA"

description: '
  '