---
title: MongoDB
tags:
    - database
    - nosql
documentation: http://docs.mongodb.org/manual/

configuration: 
    user:
        default: mongodb
        description: Mongodb running user.
        type: string
        required: false
    enable:
        default: "yes"
        description: Enable or disable mongodb service.
        type: string
        required: false
        enum:
            - "yes"
            - "no"
    dbpath:
        default: /var/lib/mongodb
        description: Database files path.
        type: string
        required: false
    logpath:
        default: /var/log/mongodb/mongodb.log
        description: Database log file path.
        type: string
        required: false
    bindip:
        default: 127.0.0.1
        description: Binding IP address.
        type: string
        required: false
    port:
        default: 27017
        description: Connection port.
        type: integer
        required: false
        minimum: 1025
        maximum: 65536
    nohttp:
        default: "false"
        description: Disable entirely the HTTP interface.
        type: string
        required: false
        enum:
            - "true"
            - "false"
    enable_rest:
        default: false
        description: Enable REST over the HTTP interface
        type: boolean
        required: false
    users:
        default: []
        description: Array of MongoDB admin db users. Passwords are randomly generated. 
          A global admin user (named admin) is created automatically.
          The users defined here will be admin users of their respective databases
        object_id: user
        required: false
        type: array
        options:
            name:
                default: null
                description: User name
                required: true
                type: string
            databases:
                default: []
                description: Array of database names where the user will be an admin
                required: false
                type: array
    databases:
        default: []
        description: Array of databases, defines a database and the list of users with only read-write access
        object_id: database
        required: false
        type: array
        options:
            name:
                default: null
                description: Database name
                required: true
                type: string
            users:
                default: []
                description: Array of users with read-write privileges on the database. 
                  If the user does not exist it will be created. 
                  Do not specify users that are already admin of the database or they will loose their admin privileges.
                required: false
                type: array
