---
# file: services/apache/handlers/main.yml

# Ensure service enabled at boot
- name: enable apache service
  service: name=apache2 enabled=yes

- name: restart apache
  service: name=apache2 state=restarted

- name: reload apache
  service: name=apache2 state=reloaded
