---
# Expects to be triggerd via task with

- name: Add Supervisor program
  sudo: yes
  template: 
    src=DEVOPS_PACKAGE/templates/program.conf.j2
    dest=/etc/supervisor/conf.d/{{ task.supervisor.program_add.name }}.conf
    owner=root
    group=root
    mode=644
  notify: Restart the Supervisor program

# Register the vhost to the devops registry
- name: Register Supervisor program
  local_action:
    module: shell
      echo REGISTER_SUPERVISOR_PROGRAM "{{ task.supervisor.program_add.name }}"
