---
- hosts: all
  gather_facts: False
  tasks:
    - name: Ensure Rackspace server
      action:
        module: rax 
        image: ${ami}
        flavor: ${flavor}
        region: ${region}
        name: "${inventory_hostname}"
        wait: yes
        wait_timeout: 500
      delegate_to: 127.0.0.1
      when_string: ${type} == 'ec2'
