---
# Expects to be triggerd via task with

- name: Add Supervisord program configuration
  sudo: yes
  template: 
    src=DEVOPS_PACKAGE/templates/program.conf.j2
    dest=/etc/supervisor/conf.d/{{ task.supervisord.program_add.name }}.conf
    owner=root
    group=root
    mode=644

- name: Add the program to Supervisord
  sudo: yes
  supervisorctl: 
    name={{ task.supervisord.program_add.name }}
    state=present
  register: program_added

- name: Restart the program if present already
  sudo: yes
  supervisorctl: 
    name={{ task.supervisord.program_add.name }}
    state=restarted
  when:
    program_added.changed and task.supervisord.program_add.autostart is not defined or task.supervisord.program_add.autostart


# Register the vhost to the devops registry
- name: Register Supervisord program
  local_action:
    module: shell
      echo REGISTER_SUPERVISORD_PROGRAM "{{ task.supervisord.program_add.name }}"
