---
- name: Prepare client folder
  file:
    state=directory
    recurse=yes
    path=/etc/openvpn/clients/{{ openvpn_user }}
    owner=root
    group=root

- name: Prepare openvpn client config
  template:
    src=DEVOPS_PACKAGE/templates/client.ovpn.j2
    dest=/etc/openvpn/clients/{{ openvpn_user }}/{{ openvpn_user }}.ovpn
    owner=root
    group=root
    mode=0644

- name: Copy script to generate openvpn server key
  copy:
    src=DEVOPS_PACKAGE/files/create_openvpn_user.sh
    dest=/root/create_openvpn_user.sh
    owner=root
    group=root
    mode=0644

- name: Create OpenVPN user
  command:
    bash /root/create_openvpn_user.sh {{ openvpn_user }}

- name: Sends email with credentials
  mail:
    subject="["{{ ansible_hostname }}"] Your openvpn access"
    body="Please find attached your openvpn access"
    attach="/etc/openvpn/clients/"{{ openvpn_user }}".tar.gz"
    to={{ openvpn_user_email }}
