---
variables:
    dbpath:
        default: /var/lib/mongodb
        description: Database files path.
    logpath:
        default: /var/log/mongodb/mongodb.log
        description: Database log file path.
    bindip:
        default: 127.0.0.1
        description: Binding IP address.
    port:
        default: 27017
        description: Connection port.
