---
variables:
    dbpath:
        default: /var/lib/mongodb
        description: Database files path.
        type: string
        required: false
    logpath:
        default: /var/log/mongodb/mongodb.log
        description: Database log file path.
        type: string
        required: false
    bindip:
        default: 127.0.0.1
        description: Binding IP address.
        type: string
        required: false
    port:
        default: 27017
        description: Connection port.
        type: integer
        required: false
        minimum: 1025
        maximum: 65536
