---
- name: Add uwsgi app
  sudo: yes
  template:
    src=DEVOPS_PACKAGE/templates/uwsgi.ini.j2
    dest=/etc/uwsgi/{{ task.uwsgi.app_add.name }}.ini
    owner=root
    group=root
    mode=0755
  # notify:
  #   - Ensure Emperor is enabled
  #   - Restart Emperor