---
- name: Ensure the virtualenvs folder exists
  sudo: yes
  file:
    state=directory
    path=/opt/virtualenvs
    owner=devops
    group=devops
    mode=755
  when: task.uwsgi.requirements_file

- name: Ensure virtualenv
  sudo: yes
  pip:
    requirements: "{{ task.uwsgi.requirements_file }}"
    virtualenv: /opt/virtualenvs/devops_{{ task.uwsgi.app_add.name }}
  when: task.uwsgi.requirements_file

- name: Add uwsgi app
  sudo: yes
  template:
    src=DEVOPS_PACKAGE/templates/uwsgi.ini.j2
    dest=/etc/uwsgi/{{ task.uwsgi.app_add.name }}.ini
    owner=root
    group=root
    mode=0755
  notify:
    - Ensure Emperor is enabled
    - Restart Emperor