---
- name: Ensure mysql databases
  mysql_db:
    name={{ item.key }}
    state=present
  with_dict:
    mysql.databases | default({})

- name: Ensure user's grants to the databases
  mysql_user:
    name={{ item.1 }}
    append_privs=yes
    priv={{ item.0 }}.*:ALL
    state=present
  when:
    item.1 in mysql.databases[item.0].users
  with_nested:
    - "{% set dbs = mysql.databases.iterkeys() %}{{ dbs | list }}"
    - "{% set users = mysql.users.iterkeys() %}{{ users | list }}"
