---
- name: Ensure mysql databases
  mysql_db:
    name={{ item.key }}
    state=present
  with_dict:
    mysql.databases | default({})

# - name: Ensure user's grants to the databases
#   mysql_user:
#     name={{ item.1 }}
#     append_privs=yes
#     priv={{ item.0.key }}.*:ALL
#     state=present
#   with_subelements:
#     - mysql.databases
#     - users


- name: Ensure user's grants to the databases
  shell:
    "echo '{{ item.1 }}' >> /tmp/toto ; echo '{{ item.0 }}.*:ALL' >> /tmp/toto"
  with_nested:
    ${item.key}
    ${item.users}
  with_dict:
    mysql.databases


- name: Ensure user's grants to the databases
  mysql_user:
    name={{ item.1 }}
    append_privs=yes
    priv={{ item }}.*:ALL
    state=present
  with_items:
    item.users
  with_dict:
    mysql.databases
