---
- name: Prepare backup folder
  # TODO: register the path so we can use for all the backup files
  sudo: yes
  file:
    path: /opt/backup/mysql
    state: directory

- name: Backup and compress the MySQL databases (individual)
  sudo: yes
  shell:
    mysqldump --opt --routines --triggers --events --flush-privileges \
              --skip-add-drop-table --master-data=2 --dump-date --databases {{ item }} \
              | gzip > /opt/backup/mysql/{{ item }}_$(date "+%s").sql.gz
  with_items:
    # By default array with empty value so all DB are exported at once
    task.mysql.database_backup.name
  when:
    task.mysql.database_backup is defined and task.mysql.database_backup.name is defined


- name: Backup and compress the MySQL databases (all)
  sudo: yes
  shell:
    mysqldump --opt --routines --triggers --events --flush-privileges \
              --skip-add-drop-table --master-data=2 --dump-date --databases \
              | gzip > /opt/backup/mysql/all_db_$(date "+%s").sql.gz
  when:
    task.mysql is not defined or task.mysql.database_backup is not defined or task.mysql.database_backup.name is not defined
