---
- name: da funk
  shell:
    echo {{ item | default('no') }} {{ item.name | default('no name') }} >&2
  with_items:
    task.mysql.user_add

- name: da funk
  shell:
    echo {{ item | default('no') }} {{ item.name | default('no name') }} >&2
  with_items:
    - task.mysql.user_add

- name: da funk
  shell:
    echo {{ item | default('no') }} {{ item.name | default('no name') }} >&2
  with_items:
    - 
    task.mysql.user_add

- name: da funk
  shell:
    echo {{ item | default('no') }} {{ item.name | default('no name') }} >&2
  with_items:
    - 
      - task.mysql.user_add

# TODO: consider when a password is provided
- name: Ensure MySQL passwords
  sudo: yes
  shell:
    if [ -f /root/.mysql_{{ task.mysql.user_add.name }}.passwd ]; then cat /root/.mysql_{{ task.mysql.user_add.name }}.passwd; else cat /dev/urandom | base64 | head -c20 | tee /root/.mysql_{{ task.mysql.user_add.name }}.passwd ; fi
  register:
    mysql_pass

- name: Ensure MySQL users
  sudo: yes
  mysql_user: 
    name={{ item.1.name }}
    password={{ item.0.stdout }}
    host={{ item.2 }}
    state=present
  when:
    item.0.item.name == item.1.name
  with_nested_subelements:
    - mysql_pass.results
    - task.mysql.user_add
    - hosts
    - localhost

# Register the user/pass to the devops registry
- name: Register MySQL user
  local_action:
    module: shell
      echo REGISTER_MYSQL_USER "{{ item.0.item.name }}" "{{ item.0.stdout }}"
  when:
    item.0.item.name == item.1.name
  with_nested:
    - mysql_pass.results
    - task.mysql.user_add
