---
- name: Ensure MySQL passwords
  sudo: yes
  shell:
    if [ -f /root/.mysql_{{ item.name }}.passwd ]; then cat /root/.mysql_{{ item.name }}.passwd; else cat /dev/urandom | base64 | head -c20 | tee /root/.mysql_{{ item.name }}.passwd ; fi
  with_items:
    mysql.users | default([])
  register:
    mysql_pass

- name: Ensure MySQL users
  sudo: yes
  mysql_user: 
    name={{ item.2.name }}
    password={{ item.1.stdout }}
    host={{ item.3 }}
    state=present
  when:
    item.1.item.name == item.2.name
  with_nested_subelements:
    - mysql_pass.results
    - mysql.users
    - hosts
    - localhost

# Register the user / pass to the devops registry
- name: Register MySQL users
  local_action:
    module: shell
      echo REGISTER_MYSQL_USER "{{ item.1.item.name }}" "{{ item.1.stdout }}"
  when:
    item.1.item.name == item.2.name
  with_nested:
    - mysql_pass.results
    - mysql.users

# - name: Register MySQL users
#   local_action:
#     module: shell
#       'python push_to_registry {{ item.item.key }} {{ item.stdout }}'
#   with_items:
#     mysql_pass.results
