---
- name: Ensure MySQL users
  sudo: yes
  mysql_user: 
    name={{ item.1.name }}
    password="{{ lookup('registry_password', 'path=mysql.users.'+ item.1.name +' user_id='+ user_id +' repo='+ repo +' node_id='+ node_id +' host='+ item.2) }}"
    host={{ item.2 }}
    state=present
  with_nested_subelements:
    - [{'stuff':'whatever'}]
    - 
      - "{{ task.mysql.user_add }}"
    - hosts
    - localhost
