---
title: Ruby
experimental: true
tags:
    - language
documentation: https://www.ruby-lang.org/en/documentation/

configuration: 
    gems:
        description: List of gems to install globally on the system
        type: array
        default: []
        required: false
    versions:
        description: Dictionary of Ruby versions to install in addition to the system version of Ruby. The `keys` are the Ruby versions to install, the `values` are either an empty object `{}` to only install the Ruby version without extra gems, or an object with a `gems` attribute that lists the gems to install.
        type: object
        default: {}
        required: false

