---
title: Ruby
tags:
    - language
documentation: https://www.ruby-lang.org/en/documentation/

configuration: 
    gems:
        description: List of gems to install globally on the system
        type: array
        default: []
        required: false
