---
- name: Backup PostgreSQL database(s)
  sudo: true
  shell:
    batt {% if task.postgresql.database_backup.path is defined %}--path {{ task.postgresql.database_backup.path }}{% endif %} \
                  {% if task.postgresql.database_backup.name is defined %} --postgresql-db {{ task.postgresql.database_backup.name | join(' --postgresql-db ') }} \
                  {% else %} postgresql{% endif %}
