---
- name: Ensure Docker repo GPG key is present
  apt_key:
    url=http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x36A1D7869245C8950F966E92D8576A8BA88D21E9
    state=present

- name: Ensure Docker repo is installed
  apt_repository:
    repo='deb http://get.docker.io/ubuntu docker main'
    state=present

- name: Ensure Docker is installed
  apt:
    name=lxc-docker
    state=present
    update_cache=yes
  notify: Ensure Docker is enabled

- name: Ensure Docker configuration is set
  template:
    src=DEVOPS_PACKAGE/templates/docker_default.j2
    dest=/etc/default/docker
    owner=root
    group=root
    mode=0400
  notify: Restart Docker

- name: Ensure the users are part of the docker group
  user:
    name={{ item.user_id }}
    groups=docker
    state=present
  with_flattened:
    - "{{ users }}"
    - [{user_id: 'devops'}]

- include: DEVOPS_PACKAGE/tasks/start.yml

- name: Fetch docker images
  shell:
    docker pull '{{ item }}'
  with_items:
    docker.images | default([])