---
title: Docker
experimental: true
tags:
    - infrastructure
documentation: https://docs.docker.com/
dependencies:
    - supervisord

configuration: 
    dns:
        default: []
        description: Array of DNS ips to pass to Docker and each container.
        type: array
        required: false
    sock:
        default: true
        description: Enable UNIX socket for Docker service.
        type: boolean
        required: false
    inet:
        default: false
        description: Enable INET tcp for Docker service.
        type: boolean
        required: false
    inet_ip:
        default: 0.0.0.0
        description: IP address used to bind the Docker service.
        type: string
        required: false
    inet_port:
        default: 2375
        description: PORT address used to bind the Docker service.
        type: string
        required: false
    registry_mirror:
        default: ''
        description: Define the URL of the registry mirror to use.
        type: string
        required: false
    extra_args:
        default: ''
        description: Extra arguments to pass to the Docker service. E.g. "--insecure-registry x.y.z:5000".
        type: string
        required: false
