---
- name: Add Forever application
  template:
    src=DEVOPS_PACKAGE/templates/forever_app.conf.j2
    dest=/etc/forever.d/{{ item.name }}.conf
    owner=root
    group=root
    mode=0644
  with_items:
    # - { name: myapp, root: /var/www/myapp, script: app.js, node_env: production, user: nobody }
  notify:
    - start forever