---
- name: Install PHP extension via PECL
  command:
    pecl -q install {{ task.php.pecl_extension_add.name }}

- name: Add PHP extension to PHP config
  template:
    src=DEVOPS_PACKAGE/templates/pecl_extension.ini.j2
    dest={{ item }}/{{ task.php.pecl_extension_add.name }}.ini
    owner=root
    group=root
    mode=0644
  with_items:
    - /etc/php5/fpm/conf.d/
    - /etc/php5/cli/conf.d/
  notify:
    - Restart php5-fpm
    #- restart apache