---
- name: Prepare backup folder
  # TODO: register the path so we can use for all the backup files
  sudo: yes
  file:
    path: /opt/backup/file
    state: directory

- name: Backup and compress files / folders
  sudo: yes
  shell:
    tar czvf /opt/backup/file/{{ task.backup.file_archive.name }}_$(date "+%s").tar.gz {{ task.backup.file_archive.files | join(' ') }}
  when:
    task.backup.file_archive.files is defined
