---
# get backup_prefix.stdout
- include: DEVOPS_BASE/services/backup/latest/tasks/register.yml

- name: Prepare backup folder for files
  # TODO: register the path so we can use for all the backup files
  sudo: yes
  file:
    path: '{{ backup_prefix.stdout }}/file'
    state: directory

- name: Backup and compress files / folders
  sudo: yes
  shell:
    tar czvf {{ backup_prefix.stdout }}/file/{{ task.backup.file_archive.name }}_$(date "+%s").tar.gz {{ task.backup.file_archive.files | join(' ') }}
  when:
    task.backup.file_archive.files is defined
