---
- name: Disable default services for backup
  sudo: true
  shell:
    batt disable {{ backup.services.disable | join(' ') }}
  when: backup.services is defined and backup.services.disable is defined