# Couchbase

[Official site](http://www.couchbase.com/)

Couchbase Server is the leading enterprise NoSQL database for scalability, performance, and availability.

## Configuration example

```yaml
services:
  couchbase: '*'
configuration:
  couchbase: {}
```
---
{}
---
