---
# file: common/tasks/dependencies.yml

# Ensure troubleshooting tools

- name: Ensure python-apt is installed
  shell: 
    creates=/home/devops/.ansible/python-apt
    /usr/bin/apt-get install -y python-apt-common && touch /home/devops/.ansible/python-apt

- name: Ensure dependencies for apt_repository are installed
  apt: 
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - python-software-properties
    - python-pycurl

- name: Ensure proper locales are generated
  shell:
    locale-gen en_US.UTF-8

- name: Ensure locales are enabled
  lineinfile:
    dest=/etc/default/locale
    line='LC_ALL="en_US.UTF-8"'
    state=present

# Ensure more...
