---
# file: common/tasks/dependencies.yml

# Ensure troubleshooting tools

- name: install python-apt
  shell: 
    creates=/home/devops/.ansible/python-apt
    /usr/bin/apt-get install -y python-apt && touch /home/devops/.ansible/python-apt

- name: install dependencies for apt_repository
  apt: 
    name={{ item }}
    state=present
    update_cache=yes
  with_items:
    - python-software-properties
    # should use pip for pycurl?
    - python-pycurl

- name: Ensure proper locales
  shell:
    locale-gen en_US.UTF-8

- name: Ensure locales are being used
  lineinfile:
    dest=/etc/default/locale
    regexp='^LC_ALL="en_US.UTF-8"'
    state=present

# Ensure more...