---
- name: Ensure devops repo GPG key
  apt_key:
    url=http://repo.devo.ps/ubuntu/repo.devo.ps.gpg.key
    state=present

- name: Ensure devops repo
  get_url:
    dest=/etc/apt/sources.list.d/
    url=http://repo.devo.ps/ubuntu/repo_devo_ps_{{ ansible_distribution_release }}.list
    mode=644

- name: Ensure devops-etcd
  apt:
    name=devops-etcd
    state=present
    update_cache=yes

- name: Ensure devops folders
  file:
    state=directory
    path={{ item }}
    recurse=yes
    owner=devops
    group=root
    mode=750
  with_items:
    - /opt/devops/etc/profile.d

- name: Ensure env file
  command:
    creates=/opt/devops/etc/profile.d/devops.sh
    touch /opt/devops/etc/profile.d/devops.sh

- name: Ensure the profile 
  file:
    state=link
    src=/opt/devops/etc/profile.d/devops.sh
    dest=/etc/profile.d/devops.sh
    owner=root
    group=root
    mode=777

- name: Ensure etcd config file
  lineinfile:
    dest=/etc/default/devops-etcd
    state=present
    regexp='^NODE_NAME={{ inventory_hostname }}'
    line='NODE_NAME={{ inventory_hostname }}'
    insertafter='^NODE_NAME='
  notify: restart devops-etcd

- name: Enable devops-etcd script
  service:
    name=devops-etcd
    enabled=yes

- name: Ensure devops-etcd is running
  service:
    name=devops-etcd
    state=running

- name: Ensure python requests module is installed
  apt:
    name=python-requests
    state=present

- name: Register inventory to etcd
  script: 
    DEVOPS_PACKAGE/files/register_to_etcd.py {{ hostvars[inventory_hostname] | to_json | b64encode }}