---
- name: Ensure devops repo
  apt_repository:
    repo='deb http://repo.devo.ps/ amd64/'
    state=present

- name: Remove deb-src for devops repo
  lineinfile:
    dest=/etc/apt/sources.list
    regexp='^deb-src http://repo.devo.ps'
    state=absent

- name: Ensure devops-etcd
  apt:
    name=devops-etcd
    state=present
    update_cache=yes
    force=yes

- name: Ensure devops folders
  file:
    state=directory
    path={{ item }}
    recurse=yes
    owner=devops
    group=root
    mode=750
  with_items:
    - /opt/devops/etc/profile.d

- name: Ensure env file
  command:
    creates=/opt/devops/etc/profile.d/devops.sh
    touch /opt/devops/etc/profile.d/devops.sh

- name: Ensure the profile 
  file:
    state=link
    src=/opt/devops/etc/profile.d/devops.sh
    dest=/etc/profile.d/devops.sh
    owner=root
    group=root
    mode=777

- name: Ensure etcd config file
  lineinfile:
    dest=/etc/default/devops-etcd
    state=present
    regexp='^NODE_NAME={{ inventory_hostname }}'
    line='NODE_NAME={{ inventory_hostname }}'
    insertafter='^NODE_NAME='
  notify: restart devops-etcd

- name: Enable devops-etcd script
  service:
    name=devops-etcd
    enabled=yes

- name: Ensure devops-etcd is running
  service:
    name=devops-etcd
    state=running