- name: 
  script:
    common/files/fetch_etcd_var.sh {{ data.host }} {{ data.keys }}
  with_items:
    to_be_fetched



# to_be_fetched = [
#     {
#         host: db1 -- IP  (meta)
#         keys: [ DEVOPS_DB1_MYSQL_CONFIG_PORT, key2, key3]
#     },
#     {
#         host: web1
#         keys: [ key1, key2, key3]
#     }
# ]
