---
# file: common/tasks/kernel.yml

# Ensure users
- name: Ensure swappiness is set to 0
  sysctl: 
    name=vm.swappiness
    value=0
    reload=yes
    state=present

- name: Ensure limits nofile is set to 64K
  file: 
    src=DEVOPS_PACKAGE/files/limits.nofile.conf
    dest=/etc/security/limits.d/nofile.conf
    owner=root
    group=root
    mode=0644