---
# file: common/tasks/kernel.yml

# Ensure users
- name: Ensure swappiness is set to 0
  sysctl: 
    name=vm.swappiness
    value=0
    reload=yes
    state=present

- name: Ensure limits nofile is set to 64K
  copy: 
    src=DEVOPS_PACKAGE/files/limits.nofile.conf
    dest=/etc/security/limits.d/nofile.conf
    owner=root
    group=root
    mode=0644

# Need some swap somewhere
- name: Ensure a poor man's SWAP file is available
  shell:
    creates={{ item }}
    dd if=/dev/zero of={{ item }} bs=1M count=2048; mkswap {{ item }}
  with_items:
    - /swapfile

- name: Ensure proper permissions for the SWAP file
  file:
    path={{ item }}
    owner=root
    group=root
    mode=0600
    state=file
  with_items:
    - /swapfile

- name: Ensure the SWAP file is used at boot
  lineinfile: 
    dest=/etc/fstab
    regexp="^{{ item }}"
    line="{{ item }}    swap    swap    defaults    0 0"
    state=present
  when:
    - /swapfile

- name: Ensure the SWAP is used
  command:
    swapon -a
