---
# file: common/tasks/packages.yml

# Ensure troubleshooting tools
- name: Ensure we have apt updated
  apt: 
    update_cache=yes

- name: Ensure we have the latest installed packages
  apt:
    upgrade=safe

- name: Ensure troubleshooting tools are installed
  apt: 
    name={{ item }}
    state=installed
  with_items:
    - htop
    - iftop
    - sysstat
    - dstat

# Ensure code versionning tools

- name: Ensure VCS tools are installed
  apt: 
    name={{ item }} 
    state=installed
  with_items:
    - subversion
    - git

# Ensure more... 
- name: Ensure postfix is installed
  apt: 
    name=postfix
    state=installed

- name: Ensure postfix is only listening to localhost
  lineinfile:
    dest=/etc/postfix/main.cf
    regexp='^inet_interfaces'
    line='inet_interfaces = 127.0.0.1'
    state=present
  notify: restart postfix

# Ensure some of the dev tools are present
- name: Ensure dev tools
  apt:
    name={{ item }}
    state=present
  with_items:
    - make
    - gcc
    - g++
    - python-pip
