---
- name: Remove collaborator SSH keys to the devops user
  authorized_key: 
    user=devops
    state=absent
    key='{{ item }}'
    manage_dir=yes
  with_items: 
    collaborator_ssh_keys | default([])
