---
# Execute inline / scripts in tasks
- name: Copy task's script over
  template:
    src="{{ file }}"
    dest=/tmp/devops_task
    mode=0777

- name: Execute script
  shell:
    # Execute script and remove it afterhand
    # /tmp/devops_task ; rm /tmp/devops_task
    /tmp/devops_task


