---
# Ensure users
- name: Ensure devops user exists
  user: 
    name=devops
    state=present
    comment='Devo.ps admin user'
    home=/home/devops
    shell=/bin/bash

- name: Ensure /etc/profile is loaded for devops user
  lineinfile:
    dest=/home/devops/.bashrc
    state=present
    regexp='^\. /etc/profile'
    line='. /etc/profile'
    insertbefore=BOF

- name: Ensure devops has the correct authorized_key
  authorized_key: 
    user=devops
    state=present
    key='{{ ssh.devops }}'
    manage_dir=yes

- name: Ensure devops user can sudo
  copy: 
    src=DEVOPS_PACKAGE/files/10-devops 
    dest=/etc/sudoers.d/10-devops 
    owner=root
    group=root
    mode=440

# Ensure customer users
- name: Ensure profile user exists
  user: 
    name={{ space }}
    state=present
    comment='Devo.ps {{ space }} user'
    home=/home/{{ space }}
    shell=/bin/bash

- name: Ensure profile user has the correct authorized_keys
  authorized_key: 
    user={{ space }}
    state=present
    key='{{ item.key }}'
    manage_dir=yes
  with_items:
    keys

- name: Ensure profile user can sudo
  template: 
    src=DEVOPS_PACKAGE/templates/10-customer.j2 
    dest=/etc/sudoers.d/10-{{ space }}
    owner=root
    group=root
    mode=440

