---
# Ensure customer users
- name: Ensure user exists
  user: 
    name="{{ item.user }}"
    state=present
    comment="Devo.ps {{ item.user }} user"
    home="/home/{{ item.user }}"
    shell=/bin/bash
  with_items: linux_users

- name: Ensure profile user has the correct authorized_keys
  authorized_key: 
    user={{ item.0.user }}
    state=present
    key='{{ item.1.key }}'
    manage_dir=yes
  with_subelements:
   - linux_users
   - keys

- name: Ensure profile user can sudo
  template: 
    src=DEVOPS_PACKAGE/templates/10-customer.j2 
    dest=/etc/sudoers.d/10-{{ item.user }}
    owner=root
    group=root
    mode=440
  with_items: linux_users

