# Ruby

[Official site](https://www.ruby-lang.org/en/)

A dynamic, open source programming language with a focus on simplicity and productivity. It has an elegant syntax that is natural to read and easy to write.

---
gems: []
---
