---
- name: Add forever application
  sudo: yes
  template:
    src=DEVOPS_PACKAGE/templates/forever_app.conf.j2
    dest=/etc/forever.d/{{ item.name }}.conf
    owner=root
    group=root
    mode=0644
  with_items:
    - "{{ task.forever.app_add }}"
  notify:
    - Restart forever