---
- name: restart postfix
  service: name=postfix state=restarted

- name: reload postfix
  service: name=postfix state=reloaded

- name: start postfix
  service: name=postfix state=started

- name: stop postfix
  service: name=postfix state=stopped

- name: enable postfix
  service: name=postfix enabled=yes

- name: disable postfix
  service: name=postfix enabled=no