---
- name: Ensure MongoDB read-write users
  mongodb_user: 
    user={{ item.1 }}
    password="{{ lookup('registry_password', 'path=mongodb.users.'+ item.1 +' user_id='+ user_id +' repo='+ repo +' node_id='+ node_id) }}"
    login_user=admin
    login_password="{{ lookup('registry_password', 'path=mongodb.users.admin user_id='+ user_id +' repo='+ repo +' node_id='+ node_id) }}"
    database={{ item.0.name }}
    roles=readWrite
    state=present
  with_nested:
    - mongodb.databases
    - users
