---
# file: common/tasks/users.yml

# Ensure users
- name: be sure devops user exists
  user: name=devops state=present comment='Devo.ps admin user' home=/home/devops

- name: be sure devops has the correct authorized_key
  authorized_key: user=devops state=present key='$FILE(/home/devops/.ssh/id_rsa.pub)'

- name: be sure devops user can sudo
  copy: src=../files/10-devops dest=/etc/sudoers.d/10-devops owner=root mode=440

# - name: be sure devops has a .ssh folder
#   file: path=/home/devops/.ssh state=directory owner=devops group=devops mode=600
# 
# - name: be sure devops user can ssh
#   copy: src=../files/devops.id_rsa dest=/etc/sudoers.d/10-devops owner=devops mode=400
