---
# file: services/mysql/tasks/mysql-server.yml

# Ensure packages
- name: be sure mysql-server is installed
  apt: pkg=mysql-server state=present

- name: be sure python-mysqldb is installed
  apt: pkg=python-mysqldb state=present

# Ensure config
# Do some shit about the config
- name: ensure mysql-server configuration
  template: src=${base}/services/mysql/templates/my.cnf.j2 dest=/etc/mysql/my.cnf owner=root mode=0640
  notify: restart mysql-server

# Ensure running
- name: be sure mysql-server is running
  service: name=mysql state=started

# Ensure root password
- name: retrieve or generate root password
  shell: export FILE='/home/devops/.ansible/mysql_root_password' && [ -f $FILE ] && cat $FILE || ( openssl passwd -in /dev/urandom | head -1 | tee $FILE )
  register: mysql_root_password

- name: be sure mysql has a root password
  mysql_user: name=root password=${mysql_root_password.stdout} priv=*.*:ALL state=present
  
- name: be sure we have a .my.cnf in the root folder
  template: src=${base}/services/mysql/templates/client.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0400 password=mysql_root_password.stdout
