---
# file: common/tasks/dependencies.yml

# Ensure troubleshooting tools

- name: install python-apt
  shell: 
    creates=/home/devops/.ansible/python-apt
    /usr/bin/apt-get install -y python-apt && touch /home/devops/.ansible/python-apt

- name: install dependencies for apt_repository
  apt: 
    name=python-software-properties
    state=present
# Ensure more...