---
# file: common/tasks/packages.yml

# Ensure troubleshooting tools
- name: Ensure we have apt updated
  apt: update_cache=yes

- name: Ensure troubleshooting tools are installed
  apt: pkg=$item state=installed
  with_items:
    - htop
    - iftop
    - sysstat
    - dstat

# Ensure code versionning tools

- name: Ensure VCS tools are installed
  apt: pkg=$item state=installed
  with_items:
    - subversion
    - git

# Ensure more... 
- name: Ensure postfix is installed
  apt: pkg=postfix state=installed