---
# file: services/mongodb/tasks/main.yml

# Ensure packages
# - name: Ensure we have apt updated
#   apt: update_cache=yes
  
- name: Ensure mongodb is installed
  apt: pkg=mongodb state=present
  notify: enable mongodb service

# Ensure config
- name: ensure the mongodb config file
  template: src=${base}/services/mongodb/templates/mongodb.conf.j2 dest=/etc/mongodb.conf owner=root group=root mode=0644
  notify: restart mongodb

# Ensure running
- name: Ensure mongodb is running
  service: name=mongodb state=started
