---
# Expects to be triggerd via task with

- name: Add HTTP vhost
  template: 
    src=DEVOPS_PACKAGE/templates/vhost_http.j2
    dest=/etc/nginx/sites-available/{{ nginx_vhost_domain }}
    owner=root
    group=root
    mode=644

- name: Enable HTTP vhost
  file:
    state=link
    src=/etc/nginx/sites-available/{{ nginx_vhost_domain }}
    dest=/etc/nginx/sites-enabled/{{ nginx_vhost_domain }}
    owner=root
    group=root
    mode=644

- name: Ensure the root folder exists
  file:
    state=directory
    path=/var/www/{{ nginx_vhost_domain }}
    owner=devops
    group=devops
    mode=755

- include: DEVOPS_PACKAGE/tasks/restart.yml