---
# file: services/mysql/tasks/mysql-server.yml

# Ensure packages
- name: be sure mysql-server is installed
  apt: pkg=mysql-server state=present

- name: be sure python-mysqldb is installed
  apt: pkg=python-mysqldb state=present

# Ensure config
# Do some shit about the config

# Ensure running
- name: be sure mysql-server is running
  service: name=mysql-server state=started

# Ensure root password
- name: be sure mysql has a root password
  mysql_user: name=root password=$mysql_root_password priv=*.*:ALL state=present
  
- name: be sure we have a .my.cnf in the root folder
  template: src=../templates/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0400
