---
id: ec2
label: Amazon AWS EC2
version: "0.2"

url_referral: ''
url_apikey: 'https://console.aws.amazon.com/iam/home?#users'
url_provider: https://aws.amazon.com

credentials:
    - label: Amazon EC2 access key ID
      id: accessKeyId
      private: false
    - label: Amazon EC2 secret key ID
      id: secretKeyId
      private: true

sizes:
    - label: T1 Micro (up to 2 ECUs - 1 Core - 613 MiB)
      id: t1.micro
    - label: M1 Small (1 ECU - 1 Core - 1.7 GiB)
      id: m1.small
    - label: M1 Medium (2 ECUs - 1 Core - 3.7 GiB)
      id: m1.medium
    - label: M1 Large (4 ECUs - 2 Cores - 7.5 GiB)
      id: m1.large
    - label: M1 Extra Large (8 ECUs - 4 Cores - 15 GiB)
      id: m1.xlarge
    - label: M3 Extra Large (13 ECUs - 4 Cores - 15 GiB)
      id: m3.xlarge
    - label: M3 Double Extra Large (26 ECUs - 8 Cores - 30 GiB)
      id: m3.2xlarge
    - label: M2 High-Memory Extra Large (6.5 ECUs - 2 Cores - 17.1 GiB)
      id: m2.xlarge
    - label: M2 High-Memory Double Extra Large (13 ECUs - 4 Cores - 34.2 GiB)
      id: m2.2xlarge
    - label: M2 High-Memory Quadruple Extra Large (26 ECUs - 8 Cores - 68.4 GiB)
      id: m2.4xlarge
    - label: C1 High-CPU Medium (5 ECUs - 2 Cores - 1.7 GiB)
      id: c1.medium
    - label: C1 High-CPU Extra Large (20 ECUs - 8 Cores - 7 GiB)
      id: c1.xlarge
    - label: High I/O Quadruple Extra Large (35 ECUs - 16 Cores - 60.5 GiB)
      id: hi1.4xlarge
    - label: High Storage Eight Extra Large (26 ECUs - 16 Cores - 117 GiB)
      id: hs1.8xlarge

locations:
    - label: Asia Pacific (Tokyo)
      id: ap-northeast-1
    - label: Asia Pacific (Singapore)
      id: ap-southeast-1
    - label: Asia Pacific (Sydney)
      id: ap-southeast-2
    - label: EU (Ireland)
      id: eu-west-1
    - label: US East (N. Virginia)
      id: us-east-1
    - label: US West (N. California)
      id: us-west-1
    - label: US West (Oregon)
      id: us-west-2
    - label: South America (São Paulo)
      id: sa-east-1

images:
    - label: Ubuntu 12.04.4 LTS 64bit (EBS)
      id: ubuntu12.04_ebs
    - label: Ubuntu 12.04.4 LTS 64bit (Instance)
      id: ubuntu12.04_ebs
    - label: Ubuntu 14.04 LTS 64bit (EBS)
      id: ubuntu14.04_ebs
    - label: Ubuntu 14.04 LTS 64bit (Instance)
      id: ubuntu14.04

# Images IDs are available at http://cloud-images.ubuntu.com/
image_ids:
    ubuntu12.04:
        ap-northeast-1: ami-77530e76
        ap-southeast-1: ami-2a257d78
        ap-southeast-2: ami-dd2147e7
        eu-west-1: ami-2f5b8a58
        us-east-1: ami-b0b37bd8
        us-west-1: ami-a9999aec
        us-west-2: ami-f199e1c1
        sa-east-1: ami-63bf167e
        default: null
    ubuntu12.04_ebs:
        ap-northeast-1: ami-df471ade
        ap-southeast-1: ami-e45800b6
        ap-southeast-2: ami-7d2f4947
        eu-west-1: ami-7d43920a
        us-east-1: ami-6ec20a06
        us-west-1: ami-039d9e46
        us-west-2: ami-d39ce4e3
        sa-east-1: ami-55be1748
        default: null
    ubuntu14.04:
        ap-northeast-1: ami-a7e4b6a6
        ap-southeast-1: ami-be3d65ec
        ap-southeast-2: ami-2bddba11
        eu-west-1: ami-2f16c758
        us-east-1: ami-502fe638
        us-west-1: ami-bbf4f7fe
        us-west-2: ami-8f4139bf
        sa-east-1: ami-b9a108a4
        default: null
    ubuntu14.04_ebs:
        ap-northeast-1: ami-6decbe6c
        ap-southeast-1: ami-b63068e4
        ap-southeast-2: ami-c7dcbbfd
        eu-west-1: ami-4d02d33a
        us-east-1: ami-6a3ff602
        us-west-1: ami-1bf8fb5e
        us-west-2: ami-2d453d1d
        sa-east-1: ami-a9a009b4
        default: null
