---
id: ec2
label: Amazon AWS EC2
version: "0.2"

url_referral: ''
url_apikey: 'https://console.aws.amazon.com/iam/home?#users'
url_provider: https://aws.amazon.com

credentials:
    - label: Amazon EC2 access key ID
      id: accessKeyId
      private: false
    - label: Amazon EC2 secret key ID
      id: secretKeyId
      private: true

sizes:
    - label: T1 Micro (up to 2 ECUs - 1 Core - 613 MiB)
      id: t1.micro
    - label: M1 Small (1 ECU - 1 Core - 1.7 GiB)
      id: m1.small
    - label: M1 Medium (2 ECUs - 1 Core - 3.7 GiB)
      id: m1.medium
    - label: M1 Large (4 ECUs - 2 Cores - 7.5 GiB)
      id: m1.large
    - label: M1 Extra Large (8 ECUs - 4 Cores - 15 GiB)
      id: m1.xlarge
    - label: M3 Extra Large (13 ECUs - 4 Cores - 15 GiB)
      id: m3.xlarge
    - label: M3 Double Extra Large (26 ECUs - 8 Cores - 30 GiB)
      id: m3.2xlarge
    - label: M2 High-Memory Extra Large (6.5 ECUs - 2 Cores - 17.1 GiB)
      id: m2.xlarge
    - label: M2 High-Memory Double Extra Large (13 ECUs - 4 Cores - 34.2 GiB)
      id: m2.2xlarge
    - label: M2 High-Memory Quadruple Extra Large (26 ECUs - 8 Cores - 68.4 GiB)
      id: m2.4xlarge
    - label: C1 High-CPU Medium (5 ECUs - 2 Cores - 1.7 GiB)
      id: c1.medium
    - label: C1 High-CPU Extra Large (20 ECUs - 8 Cores - 7 GiB)
      id: c1.xlarge
    - label: High I/O Quadruple Extra Large (35 ECUs - 16 Cores - 60.5 GiB)
      id: hi1.4xlarge
    - label: High Storage Eight Extra Large (26 ECUs - 16 Cores - 117 GiB)
      id: hs1.8xlarge

regions:
    - label: Asia Pacific (Tokyo)
      id: ap-northeast-1
    - label: Asia Pacific (Singapore)
      id: ap-southeast-1
    - label: Asia Pacific (Sydney)
      id: ap-southeast-2
    - label: EU (Ireland)
      id: eu-west-1
    - label: US East (N. Virginia)
      id: us-east-1
    - label: US West (N. California)
      id: us-west-1
    - label: US West (Oregon)
      id: us-west-2
    - label: South America (São Paulo)
      id: sa-east-1

images:
    - label: Ubuntu 12.04.3 LTS 64bit (EBS)
      id: ubuntu12.04
    - label: Ubuntu 12.10 64bit (EBS)
      id: ubuntu12.10
    - label: Ubuntu 13.04 64bit (EBS)
      id: ubuntu13.04
    - label: Ubuntu 13.10 64bit (EBS)
      id: ubuntu13.10

# Images IDs are available at http://cloud-images.ubuntu.com/
image_ids:
    ubuntu12.04:
        ap-northeast-1: ami-df0a6dde
        ap-southeast-1: ami-a0de8bf2
        ap-southeast-2: ami-c90498f3
        eu-west-1: ami-07cb2670
        us-east-1: ami-d9a98cb0
        us-west-1: ami-0ca99f49
        us-west-2: ami-50b22960
        sa-east-1: ami-e53492f8
        default: null
    ubuntu12.10:
        ap-northeast-1: ami-e52f48e4
        ap-southeast-1: ami-70d18422
        ap-southeast-2: ami-570f936d
        eu-west-1: ami-a3e805d4
        us-east-1: ami-ef1f3a86
        us-west-1: ami-daa7919f
        us-west-2: ami-10891220
        sa-east-1: ami-a92a8cb4
        default: null
    ubuntu13.04:
        ap-northeast-1: ami-cb3959ca
        ap-southeast-1: ami-a47a2ef6
        ap-southeast-2: ami-03950a39
        eu-west-1: ami-4654bb31
        us-east-1: ami-b53012dc
        us-west-1: ami-b6ac9df3
        us-west-2: ami-8c0663bc
        sa-east-1: ami-e1a203fc
        default: null
    ubuntu13.10:
        ap-northeast-1: ami-51274050
        ap-southeast-1: ami-a0d782f2
        ap-southeast-2: ami-4d0e9277
        eu-west-1: ami-d5ec01a2
        us-east-1: ami-4b143122
        us-west-1: ami-24a69061
        us-west-2: ami-ee940fde
        sa-east-1: ami-232a8c3e
        default: null
