---
title: ElasticSearch
tags:
    - database
    - full text
documentation: http://www.elasticsearch.org/guide/

configuration: 
    bind_host:
        default: '127.0.0.1'
        description: The IP address to bind to.
        type: string
        required: false
    publish_host:
        default: '127.0.0.1'
        description: The address other nodes will use to communicate with this node.
        type: string
        required: false
    host:
        default: null
        description: Set both 'bind_host' and 'publish_host'. If defined it overrides both 'bind_host' and 'publish_host' settings.
        type: string
        required: false
    http_port:
        default: 9200
        description: Listening port for HTTP traffic
        type: integer
        required: false
        minimum: 1025
        maximum: 65536
    transport_port:
        default: 9300
        description: Listening port for inter-node traffic (cluster)
        type: integer
        required: false
        minimum: 1025
        maximum: 65536
    user:
        default: elasticsearch
        description: Running user for the elasticsearch process
        type: string
        required: false
    group:
        default: elasticsearch
        description: Running group for the elasticsearch process
        type: string
        required: false
    heap_size:
        default: 256m
        description: Heap size for the elasticsearch process (unit as 256m 1g)
        type: string
        required: false
    plugins:
        default: []
        type: array
        required: false
        description: List of extra plugins to install
