---
# Enable / Disable default vhost depending whether other vhosts are defined
- name: Disable default vhost if needed
  file:
    state=absent
    dest=/etc/nginx/sites-enabled/default
  when: nginx.vhosts is defined
  notify: Restart Nginx

- name: Enable default vhost if needed
  file:
    state=link
    src=/etc/nginx/sites-available/default
    dest=/etc/nginx/sites-enabled/default
    owner=root
    group=root
    mode=644
  when: nginx.vhosts is undefined or nginx.vhosts == {} or nginx.vhosts == []
  notify: Restart Nginx


# - name: Add HTTP vhosts
#   template: 
#     src=DEVOPS_PACKAGE/templates/vhost.j2
#     dest=/etc/nginx/sites-available/{{ item.key }}
#     owner=root
#     group=root
#     mode=644
#   with_dict:
#     nginx.vhosts | default({})
#   when:
#     nginx.vhosts is defined and nginx.vhosts is mapping
#   notify: Restart Nginx

# - name: Enable HTTP vhosts
#   file:
#     state=link
#     src=/etc/nginx/sites-available/{{ item.key }}
#     dest=/etc/nginx/sites-enabled/{{ item.key }}
#     owner=root
#     group=root
#     mode=644
#   with_dict:
#     nginx.vhosts | default({})
#   when:
#     nginx.vhosts is defined and nginx.vhosts is mapping
#   notify: Restart Nginx

# - name: Ensure the root folders exists
#   file:
#     state=directory
#     path=/var/www/{{ item.key }}
#     owner=devops
#     group=devops
#     mode=755
#   with_dict:
#     nginx.vhosts | default({})
#   when:
#     nginx.vhosts is defined and nginx.vhosts is mapping


#
# LEGACY - vhosts are array
# TODO: deprecate
#

- name: Add HTTP vhosts
  template: 
    src=DEVOPS_PACKAGE/templates/vhost_legacy.j2
    dest=/etc/nginx/sites-available/{% if item.id %}item.id{% else %}{{ item.domain | default('_') }}{% endif %}
    owner=root
    group=root
    mode=644
  with_items:
    nginx.vhosts | default([])
  # when:
  #   nginx.vhosts is defined and nginx.vhosts is not mapping
  notify: Restart Nginx

- name: Enable HTTP vhosts
  file:
    state=link
    src=/etc/nginx/sites-available/{% if item.id %}item.id{% else %}{{ item.domain | default('_') }}{% endif %}
    dest=/etc/nginx/sites-enabled/{% if item.id %}item.id{% else %}{{ item.domain | default('_') }}{% endif %}
    owner=root
    group=root
    mode=644
  with_items:
    nginx.vhosts | default([])
  # when:
  #   nginx.vhosts is defined and nginx.vhosts is not mapping
  notify: Restart Nginx

- name: Ensure the root folders exists
  file:
    state=directory
    path=/var/www/{% if item.id %}item.id{% else %}{{ item.domain | default('_') }}{% endif %}
    owner=devops
    group=devops
    mode=755
  with_items:
    nginx.vhosts | default([])
  # when:
  #   nginx.vhosts is defined and nginx.vhosts is iterable and nginx.vhosts is not string
