---
title: Fail2ban
tags:
    - security

configuration:
    ignoreip:
        type: string
        required: false
        description: Space separated list of IP address, CIDR masks or a DNS host for which Fail2ban will never block connection attempts.
