# Python

[Official site](https://www.python.org/)

Python is a programming language that lets you work quickly and integrate systems more effectively.

## Configuration example

```yaml
services:
  python: '*'
configuration:
  python:
      packages: []
```
---
packages:
    default: []
    description: List of pip packages to install globally
    type: array
---
