# Mongodb

[Official site](https://www.mongodb.org/)

MongoDB (from "humongous") is an open-source document database, and the leading NoSQL database. Written in C++, MongoDB features:

* Document-Oriented Storage

  JSON-style documents with dynamic schemas offer simplicity and power.

* Full Index Support

  Index on any attribute, just like you're used to.

* Replication & High Availability

  Mirror across LANs and WANs for scale and peace of mind.

* Auto-Sharding

  Scale horizontally without compromising functionality.

* Querying

  Rich, document-based queries.

* Fast In-Place Updates

  Atomic modifiers for contention-free performance.

* Map/Reduce

  Flexible aggregation and data processing.

* GridFS

  Store files of any size without complicating your stack.

* MongoDB Management Service

  Monitoring and backup designed for MongoDB.

* Professional Support by MongoDB

  Enterprise class support, training, and consulting available.

---
user:
    default: mongodb
    description: Mongodb running user.
    type: string
    required: false
enable:
    default: "yes"
    description: Enable or disable mongodb service.
    type: string
    required: false
    enum:
        - "yes"
        - "no"
dbpath:
    default: /var/lib/mongodb
    description: Database files path.
    type: string
    required: false
logpath:
    default: /var/log/mongodb/mongodb.log
    description: Database log file path.
    type: string
    required: false
bindip:
    default: 127.0.0.1
    description: Binding IP address.
    type: string
    required: false
port:
    default: 27017
    description: Connection port.
    type: integer
    required: false
    minimum: 1025
    maximum: 65536
nohttp:
    default: "false"
    description: Disable entirely the HTTP interface.
    type: string
    required: false
    enum:
        - "true"
        - "false"
enable_rest:
    default: false
    description: Enable REST over the HTTP interface
    type: boolean
    required: false
---
