---
- name: Restart server
  shell:
    sleep 2s && /sbin/reboot &

- name: Wait for the server to go down (reboot)
  sudo: false
  local_action: 
    wait_for host={{ inventory_hostname }} port=22 state=stopped

- name: Wait for the server to come up
  sudo: false
  local_action: 
    wait_for host={{ inventory_hostname }} port=22 delay=30
