---
- name: Stop server
  shell:
    sleep 2s && /sbin/shutdown -h now &

- name: Wait for the server to go down (shutdown)
  sudo: false
  local_action: 
    wait_for host={{ inventory_hostname }} port=22 state=stopped
