---
- name: Ensure swappiness is set to 1
  sysctl: 
    name=vm.swappiness
    value=1
    reload=yes
    state=present
  tags:
    - full_sync

- name: Ensure sysctl settings
  sysctl:
    name="{{ item.key }}"
    value="{{ item.value }}"
    state=present
    reload=yes
    sysctl_set=no
    ignoreerrors=yes
  with_dict: 
    server.sysctl | default({})
  tags:
    - full_sync
