---
- name: Ensure custom gem modules are installed
  sudo: yes
  gem:
    name={{ item }}
    state=present
    user_install=no
  with_items:
    task.ruby.gems_add.gems | default([])
  ignore_errors: yes