---
- name: Ensure custom gem packages are installed
  sudo: yes
  shell:
    bash -l -c 'rbenv shell {{ task.ruby.gems_add.ruby_version | default("system") }} && gem install --no-rdoc --no-ri --no-user-install {{ task.ruby.gems_add.gems | join(" ") }} && rbenv rehash'
  when:
    task.ruby.gems_add.gems is defined and task.ruby.gems_add.gems | length > 0
  ignore_errors: yes