---
# Ensure service enabled at boot
- include: DEVOPS_PACKAGE/tasks/enable.yml

# Ensure service restarted
- include: DEVOPS_PACKAGE/tasks/restart.yml

# Ensure program restarted
- include: DEVOPS_PACKAGE/tasks/program_restart.yml
