---
# file: services/memcached/handlers/main.yml

# Ensure service enabled at boot
- name: enable memcached service
  service: name=memcached enabled=yes
  
- name: restart memcached
  service: name=memcached state=restarted
