# Task Add_http_vhost

Add a new HTTP virtual host

---
- id:  nginx_vhost_domain
  label:  Domain Name of the virtual host
  required:  true
  default:  _

- id:  nginx_vhost_webroot
  label:  Webroot within the vhost folder
  required:  true
  default:  /

- id:  nginx_vhost_port
  label:  Listening TCP port for the virtual host
  required:  false
  default:  80

- id:  nginx_vhost_php
  label:  Enable php (on/off)
  required:  false
  default:  off

- id:  nginx_vhost_proxy_pass
  label:  Proxy pass URL
  required:  false
  default:  

- id:  nginx_websocket_path
  label:  Websocket path in the domain
  required:  false
  default:  

- id:  nginx_websocket_proxy_pass
  label:  Websocket Proxy pass URL
  required:  false
  default:  

---
