---
- name: Prepare virtualenv folder
  sudo: yes
  file:
    state=directory
    path=/opt/virtualenvs
    owner=devops
    group=devops
    mode=755
  when: task.python.app_add.virtualenv is defined and task.python.app_add.requirements_file is defined

- name: Install packages defined in requirements.txt (in virtualenv)
  sudo: yes
  pip:
    requirements: "{{ task.python.app_add.requirements_file }}"
    virtualenv: /opt/virtualenvs/devops_{{ task.python.app_add.virtualenv }}
  when: task.python.app_add.virtualenv is defined and task.python.app_add.requirements_file is defined

- name: Install packages defined in requirements.txt (global)
  sudo: yes
  pip:
    requirements: "{{ task.python.app_add.requirements_file }}"
    virtualenv: /opt/virtualenvs/devops_{{ task.python.app_add.virtualenv }}
  when: task.python.app_add.virtualenv is not defined and task.python.app_add.requirements_file is defined

