---
- name: Ensure proper locales are generated
  shell:
    locale-gen en_US.UTF-8
  tags:
    - full_sync

- name: Ensure locales are enabled
  lineinfile:
    dest=/etc/default/locale
    line='LC_ALL="en_US.UTF-8"'
    state=present
  tags:
    - full_sync
