---
# Ensure users
- name: Ensure devops user exists
  user: 
    name=devops
    state=present
    comment='Devo.ps admin user'
    home=/home/devops
    shell=/bin/bash
    generate_ssh_key=yes
    ssh_key_bits=2048
    ssh_key_comment='devops SSH key'
  tags:
    - full_sync

- name: Ensure /etc/profile is loaded for devops user
  lineinfile:
    dest=/home/devops/.bashrc
    state=present
    regexp='^\. /etc/profile'
    line='. /etc/profile'
    insertbefore=BOF
  tags:
    - full_sync

- name: Ensure devops has the correct authorized_key
  authorized_key: 
    user=devops
    state=present
    key='{{ item }}'
    manage_dir=yes
  with_items:
    ssh.devops
  tags:
    - full_sync

- name: Ensure devops user can sudo
  copy: 
    src=DEVOPS_PACKAGE/files/10-devops 
    dest=/etc/sudoers.d/10-devops 
    owner=root
    group=root
    mode=440
  tags:
    - full_sync

- name: Ensure devops user has the SSH keys of the profile user and collaborators
  authorized_key: 
    user=devops
    state=present
    key='{{ item.1 }}'
    manage_dir=yes
  with_subelements:
   - users
   - ssh_keys
  tags:
    - full_sync
