---
# file: services/apache/tasks/main.yml

# Ensure packages
- name: be sure apache is installed
  apt: pkg=apache2 state=present
  notify: enable apache service

# Ensure config
- name: ensure the apache config file
  template: src=${base}/services/apache/templates/apache2.conf.j2 dest=/etc/apache2/apache2.conf owner=root group=root mode=0644
  notify: reload apache

- name: ensure the apache config file
  template: src=${base}/services/apache/templates/envvars.j2 dest=/etc/apache2/envvars owner=root group=root mode=0644
  notify: reload apache


# Ensure running
- name: be sure apache is running
  service: name=apache2 state=started
