---
- name: Set git config globally
  shell:
    git config --global user.name {{ task.git.config.user }}; git config --global user.email {{ task.git.config.email }}; 
  when: 
    not task.git.config.path or task.git.config.path == ''

- name: Set git config
  shell:
    chdir task.git.config.path
    git config user.name {{ task.git.config.user }}; git config user.email {{ task.git.config.email }}; 
  when: 
    task.git.config.path != ''