---
- name: Set git config globally for user name and email
  shell:
    git config --global user.name "{{ task.git.config.user | quote }}" && git config --global user.email "{{ task.git.config.email | quote }}"
  when: 
    not task.git.config.path or task.git.config.path == ''

- name: Set git config for user name and email
  shell:
    chdir={{ task.git.config.path }}
    git config user.name "{{ task.git.config.user | quote }}" && git config user.email "{{ task.git.config.email | quote }}"
  when: 
    task.git.config.path != ''
