---
- name: Commit the build result to the current branch
  shell:
    chdir={{ task.git['push'].repo }}
    git add . ; git commit -am 'Add build result'

- name: Push the build result over to the remote branch
  shell:
    chdir={{ task.git['push'].repo }}
    git subtree push --prefix {{ task.git['push'].build_dir }} origin {{ task.git['push'].version }}
