---
# Expects to be triggerd via task with
- name: Ensure github.com ssh key is known
  sudo: true
  shell:
    ssh-keyscan -H github.com >> /etc/ssh/ssh_known_hosts

- name: Ensure the destination folder for the repository exists
  file:
    path={{ task.git['update'].dest }}
    state=directory
    recurse=yes
    owner=devops
    mode=755

- name: Update git repository
  git: 
    repo={{ task.git['update'].repo }}
    dest={{ task.git['update'].dest }}
    version={{ task.git['update'].version | default('HEAD') }}