---
- hosts: all
  gather_facts: False
  tasks:
    - name: Delete digital-ocean server
      action:
        module: digital_ocean
        command: droplet
        state: absent
        id: ${provider_id}
      delegate_to: 127.0.0.1
      when_string: ${type} == 'digital-ocean'

