---
# file: initServer.yml

# This playbook is only meant to ensure the server get initialized
# and the devops user get created on the remote host.
#
# It should not be used after.
#
# It should be replaced from user / pass to SSH key

# Run initServer playbook with either of the following:
#   - if ssh user / password based
#       python bin/devops-playbook.py -i spaces/.../hosts initServer.yml \
#            -s -e newserver=__ip/host from inventory__ -u ubuntu -p ubuntu
#   - if ssh user / key based
#       python bin/devops-playbook.py -i spaces/.../hosts initServer.yml \
#            -s -e newserver=__ip/host from inventory__ -u ubuntu --private-key=PATH


- hosts: ${server}
  tasks:
    - include: services/${service}/tasks/main.yml
  handlers:
    - include: services/${service}/handlers/main.yml