---
# file: initServer.yml

# This playbook is only meant to ensure the server get initialized
# and the devops user get created on the remote host.
#
# It should not be used after.
#
# It should be replaced from user / pass to SSH key

# Run initServer playbook with either of the following:
#   - if ssh user / password based
#       python bin/devops-playbook.py -i spaces/.../hosts initServer.yml \
#            -s -e newserver=__ip/host from inventory__ -u ubuntu -p ubuntu
#   - if ssh user / key based
#       python bin/devops-playbook.py -i spaces/.../hosts initServer.yml \
#            -s -e newserver=__ip/host from inventory__ -u ubuntu --private-key=PATH


- hosts: all
  vars_files:
    - config/global.yml
  tasks:
    - include: common/tasks/dependencies.yml
    - include: common/tasks/users.yml
    - include: common/tasks/packages.yml
    - include: services/apache/tasks.yml
    - include: services/php/tasks.yml
    - include: services/php5-fpm/tasks.yml
    - include: services/nginx/tasks.yml
    - include: services/mysql/tasks.yml
    - include: services/mongodb/tasks.yml
    - include: services/memcached/tasks.yml
    - include: services/varnish/tasks.yml
    # - include: services/$item/tasks.yml
    #   with_items:
    #     - apache
    #     - php
    #     - php5-fpm
    #     - nginx
    #     - mysql
    #     - nginx
    #     - mongodb
    #     - memcached
    #     - varnish
  handlers:
    - include: services/$item/handlers.yml
      with_items:
        - apache
        - php
        - php5-fpm
        - nginx
        - mysql
        - nginx
        - mongodb
        - memcached
        - varnish
