---
- name: Prepare client folder
  sudo: yes
  file:
    state=directory
    recurse=yes
    path=/etc/openvpn/clients/{{ task.openvpn.add_user.user }}
    owner=root
    group=root

- name: Prepare openvpn client config
  sudo: yes
  template:
    src=DEVOPS_PACKAGE/templates/client.ovpn.j2
    dest=/etc/openvpn/clients/{{ task.openvpn.add_user.user }}/{{ task.openvpn.add_user.user }}.ovpn
    owner=root
    group=root
    mode=0644

- name: Copy script to generate openvpn server key
  sudo: yes
  copy:
    src=DEVOPS_PACKAGE/files/create_openvpn_user.sh
    dest=/root/create_openvpn_user.sh
    owner=root
    group=root
    mode=0644

- name: Create OpenVPN user
  sudo: yes
  command:
    bash /root/create_openvpn_user.sh {{ task.openvpn.add_user.user }}

- name: Sends email with credentials
  sudo: yes
  mail:
    subject="["{{ ansible_hostname }}"] Your openvpn access"
    body="Please find attached your openvpn access"
    attach="/etc/openvpn/clients/"{{ task.openvpn.add_user.user }}".tar.gz"
    to={{ task.openvpn.add_user.email }}
