---
- name: Prepare OpenVPN clients folder
  sudo: yes
  file:
    state=directory
    recurse=yes
    path=/etc/openvpn/clients/{{ item.name }}
    owner=root
    group=root
  with_items:
    task.openvpn.user_add.users

- name: Prepare OpenVPN clients config
  sudo: yes
  template:
    src=DEVOPS_PACKAGE/templates/client.ovpn.j2
    dest=/etc/openvpn/clients/{{ item.name }}/{{ item.name }}.ovpn
    owner=root
    group=root
    mode=0644
  with_items:
    task.openvpn.user_add.users

- name: Prepare helper script to generate OpenVPN server key
  sudo: yes
  copy:
    src=DEVOPS_PACKAGE/files/create_openvpn_user.sh
    dest=/root/create_openvpn_user.sh
    owner=root
    group=root
    mode=0644

- name: Create OpenVPN users
  sudo: yes
  command:
    bash /root/create_openvpn_user.sh {{ item.name }}
  with_items:
    task.openvpn.user_add.users

- name: Sends email with credentials
  sudo: yes
  mail:
    subject="["{{ ansible_hostname }}"] Your openvpn access"
    body="Please find attached your openvpn access"
    attach="/etc/openvpn/clients/"{{ item.name }}".tar.gz"
    to={{ item.email }}
  with_items:
    task.openvpn.user_add.users

